export const SIMPLE_ACTION_ONE_A = 'SIMPLE_ACTION_ONE_A';
export const SIMPLE_ACTION_ONE_B = 'SIMPLE_ACTION_ONE_B';
export const SIMPLE_ACTION_TWO_A = 'SIMPLE_ACTION_TWO_A';
export const SIMPLE_ACTION_TWO_B = 'SIMPLE_ACTION_TWO_B';